name: JMeter Tests
on: [push]

jobs:
  jmeter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y jmeter

      - name: Run tests
        run: |
          jmeter -n -t jmeter/test-plans/reqres-smoke.jmx \
                 -l jmeter/results/result.jtl \
                 -e -o jmeter/reports
