name: Performance Tests
on: [push]

jobs:
  jmeter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter
      - name: Run Performance Tests
        run: |
          jmeter -n -t jmeter/test-plans/reqres-smoke.jmx \
                 -l jmeter/results/reqres-smoke.jtl \
                 -e -o jmeter/reports/reqres-smoke
